### ISSUE TITLE
发现stable 生成的 完全是一个图片。。。视频不动的

### ISSUE THREAD

**Issue by theecn** [bravekingzhang/text2viedo#11]

**Comment by bravekingzhang** [comment]
加入了新的生成方式，使用大模型生成prompt，然后在生成，生成图片质量大幅提高 ，可惜还用不了  "ByteDance/SDXL-Lightning" ，不然，效果肯定很不错。

支持kimi
建议使用 "stabilityai/stable-diffusion-xl-base-1.0"
