### ISSUE TITLE
使用docker启动后，转换时报错

### ISSUE THREAD

**Issue by heureuxQ** [bravekingzhang/text2viedo#14]
192.168.65.1 - - [24/Apr/2024 02:11:47] "POST /convert HTTP/1.1" 500 -
app-1  | Traceback (most recent call last):
app-1  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
app-1  |     return self.wsgi_app(environ, start_response)
app-1  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
app-1  |     response = self.handle_exception(e)
app-1  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
app-1  |     response = self.full_dispatch_request()
app-1  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
app-1  |     rv = self.handle_user_exception(e)
app-1  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
app-1  |     rv = self.dispatch_request()
app-1  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
app-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
app-1  |   File "/app/app.py", line 21, in convert_text_to_video
app-1  |     video_path = convertTextToVideo(validate_model(model), text)
app-1  |   File "/app/text_to_video.py", line 129, in convertTextToVideo
app-1  |     clear_folder("images")
app-1  |   File "/app/text_to_video.py", line 106, in clear_folder
app-1  |     for filename in os.listdir(folder_path):
app-1  | FileNotFoundError: [Errno 2] No such file or directory: 'images'

**Comment by ashen-forest** [comment]
> 192.168.65.1 - - [24/Apr/2024 02:11:47] "POST /convert HTTP/1.1" 500 - app-1 | Traceback (most recent call last): app-1 | File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in **call** app-1 | return self.wsgi_app(environ, start_response) app-1 | File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app app-1 | response = self.handle_exception(e) app-1 | File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app app-1 | response = self.full_dispatch_request() app-1 | File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request app-1 | rv = self.handle_user_exception(e) app-1 | File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request app-1 | rv = self.dispatch_request() app-1 | File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request app-1 | return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return] app-1 | File "/app/app.py", line 21, in convert_text_to_video app-1 | video_path = convertTextToVideo(validate_model(model), text) app-1 | File "/app/text_to_video.py", line 129, in convertTextToVideo app-1 | clear_folder("images") app-1 | File "/app/text_to_video.py", line 106, in clear_folder app-1 | for filename in os.listdir(folder_path): app-1 | FileNotFoundError: [Errno 2] No such file or directory: 'images'

同样的问题，也是这样

**Comment by ghost** [comment]
`git pull` ,and `docker-compose up --build`
