### ISSUE TITLE
启动报错Not Found', 'path': '/translate'

### ISSUE THREAD

**Issue by LGQRL** [bravekingzhang/text2viedo#9]
首先安装后缺失dotenv，然后我手动安装，启动时报以下错误：
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.

经过查询，这个只是警告，但是我继续执行时报错：
127.0.0.1 - - [31/Mar/2024 10:48:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [31/Mar/2024 10:48:11] "GET /models HTTP/1.1" 200 -
127.0.0.1 - - [31/Mar/2024 10:48:11] "GET /favicon.ico HTTP/1.1" 404 -
zh-cn
{'timestamp': '2024-03-31T02:48:17.078+00:00', 'status': 404, 'error': 'Not Found', 'path': '/translate'}

**Comment by LGQRL** [comment]
经过查询，这个只是警告，但是我继续执行时报错：

**Comment by LGQRL** [comment]
127.0.0.1 - - [31/Mar/2024 10:48:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [31/Mar/2024 10:48:11] "GET /models HTTP/1.1" 200 -
127.0.0.1 - - [31/Mar/2024 10:48:11] "GET /favicon.ico HTTP/1.1" 404 -
zh-cn
{'timestamp': '2024-03-31T02:48:17.078+00:00', 'status': 404, 'error': 'Not Found', 'path': '/translate'}

**Comment by Abs985** [comment]
我也一样

**Comment by mengjianjia** [comment]
我也一样

**Comment by WillingSasi** [comment]
我也一样

**Comment by bravekingzhang** [comment]
现在已经优化了图片生成的方式了，不走翻译了，直接走大模型，生成图片效果更加好，可以试试
